function LiFi_Chat_App
% ================================================================
%                     LiFi CHAT APPLICATION
%       Visible Light Communication using OOK Modulation
%
%   HOME              -> Professional LiFi Chat
%   SIGNALS           -> TX/RX signal graphs
%   PERFORMANCE      -> BER / performance
%   CHANNEL ANALYSIS -> Optical power / channel gain
%   TRANSMISSION     -> Text/ASCII/Binary/OOK process
%
%   COMPLETE FLOW:
%
%   TEXT
%      ↓
%   ASCII
%      ↓
%   8-BIT BINARY
%      ↓
%   OOK MODULATION
%      ↓
%   LED / OPTICAL CHANNEL
%      ↓
%   CHANNEL ATTENUATION + AWGN
%      ↓
%   PHOTODIODE
%      ↓
%   THRESHOLD DETECTION
%      ↓
%   RECEIVED BINARY
%      ↓
%   ASCII
%      ↓
%   RECEIVED TEXT
%
% ================================================================

clc;
close all;

%% ================================================================
% PARAMETERS
% ================================================================

SNR_dB       = 5;

DataRate     = 10;
DataRateText = '10 kbps';

ChannelDistance = 2;

Distance = 0.5:0.5:5;

SamplesPerBit = 100;

% Optional additional error demonstration
% false = errors depend only on SNR/channel
% true  = intentionally adds extra bit errors
FORCE_ERROR_DEMO = false;

ForcedBitErrorProbability = 0.03;

%% ================================================================
% LAVENDER THEME
% ================================================================

BG          = [0.925 0.885 0.970];
BG_DARK     = [0.875 0.790 0.935];

CARD        = [0.855 0.765 0.925];
CARD_DARK   = [0.790 0.675 0.885];

LAVENDER    = [0.570 0.400 0.760];
LAVENDER2   = [0.650 0.500 0.830];

DEEP        = [0.350 0.220 0.500];

TEXT        = [0.270 0.170 0.360];
TEXT_LIGHT  = [0.400 0.300 0.490];

TX_BUBBLE   = [0.790 0.680 0.890];
RX_BUBBLE   = [0.875 0.805 0.930];

SUCCESS     = [0.200 0.580 0.380];
WARNING     = [0.650 0.470 0.120];
ERROR       = [0.700 0.250 0.350];

LED_RED     = [0.900 0.120 0.140];
LED_GREEN   = [0.180 0.650 0.350];
LED_IDLE    = [0.560 0.560 0.600];

%% ================================================================
% APPLICATION STATE
% ================================================================

txBitsGlobal = [];
rxBitsGlobal = [];

berGlobal = 0;
bitErrorsGlobal = 0;

messageHistory = {};
timeHistory = {};

transmittedHistory = {};
receivedHistory = {};

blinkState = false;

%% ================================================================
% MAIN WINDOW
% ================================================================

fig = uifigure( ...
    'Name','LiFi Chat Application', ...
    'Position',[100 50 1250 800], ...
    'Color',BG, ...
    'Resize','on', ...
    'WindowState','maximized');

%% ================================================================
% HEADER
% ================================================================

header = uipanel(fig, ...
    'Position',[20 720 1240 70], ...
    'BackgroundColor',CARD_DARK, ...
    'BorderType','none');

uilabel(header, ...
    'Text','LiFi', ...
    'Position',[25 18 80 38], ...
    'FontSize',27, ...
    'FontWeight','bold', ...
    'FontColor',DEEP);

uilabel(header, ...
    'Text','CHAT APPLICATION', ...
    'Position',[105 22 270 30], ...
    'FontSize',18, ...
    'FontWeight','bold', ...
    'FontColor',TEXT);

uilabel(header, ...
    'Text','Visible Light Communication using OOK', ...
    'Position',[400 25 420 25], ...
    'FontSize',12, ...
    'FontColor',TEXT_LIGHT);

statusDot = uilabel(header, ...
    'Text','●', ...
    'Position',[1060 27 25 25], ...
    'FontSize',16, ...
    'FontColor',SUCCESS);

statusHeader = uilabel(header, ...
    'Text','LiFi Connected', ...
    'Position',[1085 27 140 25], ...
    'FontSize',12, ...
    'FontWeight','bold', ...
    'FontColor',SUCCESS);

%% ================================================================
% TAB GROUP
% ================================================================

tabs = uitabgroup(fig, ...
    'Position',[20 60 1240 645]);

homeTab = uitab(tabs, ...
    'Title','HOME', ...
    'BackgroundColor',BG);

signalTab = uitab(tabs, ...
    'Title','SIGNALS', ...
    'BackgroundColor',BG);

performanceTab = uitab(tabs, ...
    'Title','PERFORMANCE', ...
    'BackgroundColor',BG);

channelTab = uitab(tabs, ...
    'Title','CHANNEL ANALYSIS', ...
    'BackgroundColor',BG);

transmissionTab = uitab(tabs, ...
    'Title','TRANSMISSION', ...
    'BackgroundColor',BG);

%% ================================================================
% HOME TAB
% ================================================================

%% LEFT INFORMATION PANEL

leftPanel = uipanel(homeTab, ...
    'Position',[15 20 285 595], ...
    'BackgroundColor',CARD, ...
    'BorderType','none');

uilabel(leftPanel, ...
    'Text','LiFi CONNECTION', ...
    'Position',[22 550 230 28], ...
    'FontSize',15, ...
    'FontWeight','bold', ...
    'FontColor',DEEP);

connectionCard = uipanel(leftPanel, ...
    'Position',[18 470 249 65], ...
    'BackgroundColor',RX_BUBBLE, ...
    'BorderType','none');

uilabel(connectionCard, ...
    'Text','●  CONNECTED', ...
    'Position',[15 32 210 24], ...
    'FontSize',12, ...
    'FontWeight','bold', ...
    'FontColor',SUCCESS);

uilabel(connectionCard, ...
    'Text','Optical communication link active', ...
    'Position',[15 10 220 18], ...
    'FontSize',10, ...
    'FontColor',TEXT_LIGHT);

%% LINK CONTROL

uilabel(leftPanel, ...
    'Text','LINK CONTROL', ...
    'Position',[22 430 230 25], ...
    'FontSize',13, ...
    'FontWeight','bold', ...
    'FontColor',DEEP);

controlCard = uipanel(leftPanel, ...
    'Position',[18 335 249 87], ...
    'BackgroundColor',CARD_DARK, ...
    'BorderType','none');

%% DATA RATE

uilabel(controlCard, ...
    'Text','DATA RATE', ...
    'Position',[12 55 90 20], ...
    'FontSize',10, ...
    'FontWeight','bold', ...
    'FontColor',TEXT_LIGHT);

dataRateDrop = uidropdown(controlCard, ...
    'Position',[105 52 125 25], ...
    'Items',{'5 kbps','10 kbps','20 kbps'}, ...
    'Value','10 kbps', ...
    'FontSize',11, ...
    'ValueChangedFcn',@dataRateChanged);

%% SNR

uilabel(controlCard, ...
    'Text','SNR', ...
    'Position',[12 18 90 20], ...
    'FontSize',10, ...
    'FontWeight','bold', ...
    'FontColor',TEXT_LIGHT);

snrDrop = uidropdown(controlCard, ...
    'Position',[105 15 125 25], ...
    'Items',{ ...
    '0 dB', ...
    '2 dB', ...
    '5 dB', ...
    '8 dB', ...
    '10 dB', ...
    '15 dB', ...
    '20 dB', ...
    '25 dB', ...
    '30 dB'}, ...
    'Value','5 dB', ...
    'FontSize',11, ...
    'ValueChangedFcn',@snrChanged);

%% MODULATION

uilabel(leftPanel, ...
    'Text','MODULATION', ...
    'Position',[22 305 230 25], ...
    'FontSize',13, ...
    'FontWeight','bold', ...
    'FontColor',DEEP);

modulationCard = uipanel(leftPanel, ...
    'Position',[18 270 249 32], ...
    'BackgroundColor',RX_BUBBLE, ...
    'BorderType','none');

uilabel(modulationCard, ...
    'Text','OOK  •  On-Off Keying', ...
    'Position',[15 5 220 22], ...
    'FontSize',10, ...
    'FontWeight','bold', ...
    'FontColor',TEXT);

%% SYSTEM STATUS

uilabel(leftPanel, ...
    'Text','SYSTEM STATUS', ...
    'Position',[22 240 230 25], ...
    'FontSize',13, ...
    'FontWeight','bold', ...
    'FontColor',DEEP);

systemCard = uipanel(leftPanel, ...
    'Position',[18 135 249 95], ...
    'BackgroundColor',RX_BUBBLE, ...
    'BorderType','none');

uilabel(systemCard, ...
    'Text','TRANSMITTER', ...
    'Position',[15 62 110 20], ...
    'FontSize',10, ...
    'FontWeight','bold', ...
    'FontColor',TEXT_LIGHT);

txStatus = uilabel(systemCard, ...
    'Text','● READY', ...
    'Position',[135 62 100 20], ...
    'FontSize',10, ...
    'FontWeight','bold', ...
    'FontColor',SUCCESS);

uilabel(systemCard, ...
    'Text','RECEIVER', ...
    'Position',[15 35 110 20], ...
    'FontSize',10, ...
    'FontWeight','bold', ...
    'FontColor',TEXT_LIGHT);

rxStatus = uilabel(systemCard, ...
    'Text','● READY', ...
    'Position',[135 35 100 20], ...
    'FontSize',10, ...
    'FontWeight','bold', ...
    'FontColor',SUCCESS);

uilabel(systemCard, ...
    'Text','MODULATION', ...
    'Position',[15 8 110 20], ...
    'FontSize',10, ...
    'FontWeight','bold', ...
    'FontColor',TEXT_LIGHT);

uilabel(systemCard, ...
    'Text','OOK', ...
    'Position',[135 8 100 20], ...
    'FontSize',10, ...
    'FontWeight','bold', ...
    'FontColor',DEEP);

%% TRANSMISSION DETAILS

uilabel(leftPanel, ...
    'Text','TRANSMISSION DETAILS', ...
    'Position',[22 105 230 25], ...
    'FontSize',13, ...
    'FontWeight','bold', ...
    'FontColor',DEEP);

detailsCard = uipanel(leftPanel, ...
    'Position',[18 5 249 95], ...
    'BackgroundColor',RX_BUBBLE, ...
    'BorderType','none');

uilabel(detailsCard, ...
    'Text','Channel', ...
    'Position',[15 68 90 20], ...
    'FontSize',10, ...
    'FontColor',TEXT_LIGHT);

uilabel(detailsCard, ...
    'Text','Optical', ...
    'Position',[135 68 95 20], ...
    'FontSize',10, ...
    'FontWeight','bold', ...
    'FontColor',TEXT);

uilabel(detailsCard, ...
    'Text','Data Rate', ...
    'Position',[15 43 90 20], ...
    'FontSize',10, ...
    'FontColor',TEXT_LIGHT);

dataRateDetail = uilabel(detailsCard, ...
    'Text','10 kbps', ...
    'Position',[135 43 95 20], ...
    'FontSize',10, ...
    'FontWeight','bold', ...
    'FontColor',TEXT);

uilabel(detailsCard, ...
    'Text','SNR', ...
    'Position',[15 18 90 20], ...
    'FontSize',10, ...
    'FontColor',TEXT_LIGHT);

snrDetail = uilabel(detailsCard, ...
    'Text','5 dB', ...
    'Position',[135 18 95 20], ...
    'FontSize',10, ...
    'FontWeight','bold', ...
    'FontColor',TEXT);

%% ================================================================
% RIGHT CHAT AREA
% ================================================================

rightPanel = uipanel(homeTab, ...
    'Position',[315 20 910 595], ...
    'BackgroundColor',BG_DARK, ...
    'BorderType','none');

%% CHAT HEADER

chatHeader = uipanel(rightPanel, ...
    'Position',[15 530 880 55], ...
    'BackgroundColor',CARD_DARK, ...
    'BorderType','none');

uilabel(chatHeader, ...
    'Text','LiFi Receiver', ...
    'Position',[18 27 220 25], ...
    'FontSize',15, ...
    'FontWeight','bold', ...
    'FontColor',TEXT);

uilabel(chatHeader, ...
    'Text','● Online', ...
    'Position',[18 7 110 20], ...
    'FontSize',10, ...
    'FontWeight','bold', ...
    'FontColor',SUCCESS);

uilabel(chatHeader, ...
    'Text','OOK  •  Optical Link Active', ...
    'Position',[630 18 230 25], ...
    'FontSize',10, ...
    'FontWeight','bold', ...
    'FontColor',DEEP);

%% CHAT DISPLAY

chatDisplay = uipanel(rightPanel, ...
    'Position',[15 170 880 350], ...
    'BackgroundColor',BG, ...
    'BorderType','none');

emptyText = uilabel(chatDisplay, ...
    'Text',{'No messages yet','Send a message via LiFi'}, ...
    'Position',[290 145 300 55], ...
    'HorizontalAlignment','center', ...
    'FontSize',13, ...
    'FontColor',TEXT_LIGHT);

%% OPTICAL LINK INDICATOR

linkPanel = uipanel(rightPanel, ...
    'Position',[15 120 880 40], ...
    'BackgroundColor',CARD, ...
    'BorderType','none');

ledIndicator = uilabel(linkPanel, ...
    'Text','●', ...
    'Position',[235 7 25 25], ...
    'FontSize',20, ...
    'FontColor',LED_IDLE);

uilabel(linkPanel, ...
    'Text','LED', ...
    'Position',[263 9 55 22], ...
    'FontSize',10, ...
    'FontWeight','bold', ...
    'FontColor',TEXT);

uilabel(linkPanel, ...
    'Text','──────  OPTICAL CHANNEL  ──────', ...
    'Position',[320 9 260 22], ...
    'HorizontalAlignment','center', ...
    'FontSize',10, ...
    'FontWeight','bold', ...
    'FontColor',TEXT_LIGHT);

photodiodeIndicator = uilabel(linkPanel, ...
    'Text','●', ...
    'Position',[588 7 25 25], ...
    'FontSize',20, ...
    'FontColor',LED_IDLE);

uilabel(linkPanel, ...
    'Text','PHOTODIODE', ...
    'Position',[616 9 95 22], ...
    'FontSize',10, ...
    'FontWeight','bold', ...
    'FontColor',TEXT);

linkLabel = uilabel(linkPanel, ...
    'Text','READY  •  OOK OPTICAL LINK', ...
    'Position',[710 9 155 22], ...
    'HorizontalAlignment','right', ...
    'FontSize',9, ...
    'FontWeight','bold', ...
    'FontColor',SUCCESS);

%% MESSAGE INPUT

inputPanel = uipanel(rightPanel, ...
    'Position',[15 65 880 48], ...
    'BackgroundColor',CARD_DARK, ...
    'BorderType','none');

messageBox = uieditfield(inputPanel, ...
    'text', ...
    'Position',[15 7 675 34], ...
    'FontSize',13, ...
    'FontColor',TEXT, ...
    'BackgroundColor',BG, ...
    'Placeholder','Type your message...');

sendButton = uibutton(inputPanel, ...
    'push', ...
    'Position',[705 7 160 34], ...
    'Text','SEND VIA LiFi  >', ...
    'FontSize',11, ...
    'FontWeight','bold', ...
    'FontColor',BG, ...
    'BackgroundColor',LAVENDER, ...
    'ButtonPushedFcn',@sendMessage);

%% METRIC BAR

metricPanel = uipanel(rightPanel, ...
    'Position',[15 10 880 45], ...
    'BackgroundColor',CARD, ...
    'BorderType','none');

uilabel(metricPanel, ...
    'Text','MESSAGE', ...
    'Position',[15 25 80 17], ...
    'FontSize',9, ...
    'FontWeight','bold', ...
    'FontColor',TEXT_LIGHT);

messageMetric = uilabel(metricPanel, ...
    'Text','--', ...
    'Position',[15 5 190 22], ...
    'FontSize',11, ...
    'FontWeight','bold', ...
    'FontColor',TEXT);

uilabel(metricPanel, ...
    'Text','TOTAL BITS', ...
    'Position',[225 25 100 17], ...
    'FontSize',9, ...
    'FontWeight','bold', ...
    'FontColor',TEXT_LIGHT);

bitsMetric = uilabel(metricPanel, ...
    'Text','--', ...
    'Position',[225 5 100 22], ...
    'FontSize',11, ...
    'FontWeight','bold', ...
    'FontColor',TEXT);

uilabel(metricPanel, ...
    'Text','BER', ...
    'Position',[355 25 70 17], ...
    'FontSize',9, ...
    'FontWeight','bold', ...
    'FontColor',TEXT_LIGHT);

berMetric = uilabel(metricPanel, ...
    'Text','--', ...
    'Position',[355 5 100 22], ...
    'FontSize',11, ...
    'FontWeight','bold', ...
    'FontColor',DEEP);

uilabel(metricPanel, ...
    'Text','STATUS', ...
    'Position',[510 25 70 17], ...
    'FontSize',9, ...
    'FontWeight','bold', ...
    'FontColor',TEXT_LIGHT);

statusMetric = uilabel(metricPanel, ...
    'Text','READY', ...
    'Position',[510 5 250 22], ...
    'FontSize',11, ...
    'FontWeight','bold', ...
    'FontColor',SUCCESS);

%% ================================================================
% SIGNAL TAB
% ================================================================

uilabel(signalTab, ...
    'Text','SIGNAL ANALYSIS', ...
    'Position',[25 585 350 30], ...
    'FontSize',18, ...
    'FontWeight','bold', ...
    'FontColor',DEEP);

uilabel(signalTab, ...
    'Text','Transmitted and received optical signals', ...
    'Position',[25 558 600 22], ...
    'FontSize',12, ...
    'FontColor',TEXT_LIGHT);

txCard = uipanel(signalTab, ...
    'Position',[25 315 575 225], ...
    'BackgroundColor',CARD, ...
    'BorderType','none');

uilabel(txCard, ...
    'Text','TRANSMITTED OOK SIGNAL', ...
    'Position',[18 195 320 24], ...
    'FontSize',13, ...
    'FontWeight','bold', ...
    'FontColor',DEEP);

axTX = uiaxes(txCard, ...
    'Position',[15 15 545 170], ...
    'BackgroundColor',BG);

title(axTX,'Transmitted OOK Signal');
xlabel(axTX,'Sample');
ylabel(axTX,'LED Intensity');
grid(axTX,'on');

rxCard = uipanel(signalTab, ...
    'Position',[615 315 575 225], ...
    'BackgroundColor',CARD, ...
    'BorderType','none');

uilabel(rxCard, ...
    'Text','RECEIVED OPTICAL SIGNAL', ...
    'Position',[18 195 330 24], ...
    'FontSize',13, ...
    'FontWeight','bold', ...
    'FontColor',DEEP);

axRX = uiaxes(rxCard, ...
    'Position',[15 15 545 170], ...
    'BackgroundColor',BG);

title(axRX,'Received Signal');
xlabel(axRX,'Sample');
ylabel(axRX,'Photodiode Output');
grid(axRX,'on');

bitCard = uipanel(signalTab, ...
    'Position',[25 50 1165 245], ...
    'BackgroundColor',CARD_DARK, ...
    'BorderType','none');

uilabel(bitCard, ...
    'Text','TRANSMITTED VS RECEIVED BITS', ...
    'Position',[18 215 400 24], ...
    'FontSize',13, ...
    'FontWeight','bold', ...
    'FontColor',DEEP);

axBits = uiaxes(bitCard, ...
    'Position',[15 15 1135 190], ...
    'BackgroundColor',BG_DARK);

title(axBits,'Transmitted vs Received Bits');
xlabel(axBits,'Bit Number');
ylabel(axBits,'Bit Value');
grid(axBits,'on');

%% ================================================================
% PERFORMANCE TAB
% ================================================================

uilabel(performanceTab, ...
    'Text','PERFORMANCE', ...
    'Position',[25 585 350 30], ...
    'FontSize',18, ...
    'FontWeight','bold', ...
    'FontColor',DEEP);

uilabel(performanceTab, ...
    'Text','LiFi communication quality and reliability', ...
    'Position',[25 558 600 22], ...
    'FontSize',12, ...
    'FontColor',TEXT_LIGHT);

berCard = createMetricCard( ...
    performanceTab,[25 475 270 65], ...
    'BIT ERROR RATE','0.0000');

errorCard = createMetricCard( ...
    performanceTab,[310 475 270 65], ...
    'BIT ERRORS','0');

snrCard = createMetricCard( ...
    performanceTab,[595 475 270 65], ...
    'SNR','5 dB');

throughputCard = createMetricCard( ...
    performanceTab,[880 475 270 65], ...
    'THROUGHPUT','10 kbps');

axBER = uiaxes(performanceTab, ...
    'Position',[35 50 780 390], ...
    'BackgroundColor',BG);

title(axBER,'LiFi System Performance: BER vs Distance');
xlabel(axBER,'Distance (m)');
ylabel(axBER,'Bit Error Rate (BER)');
grid(axBER,'on');

perfPanel = uipanel(performanceTab, ...
    'Position',[840 50 340 390], ...
    'BackgroundColor',CARD, ...
    'BorderType','none');

uilabel(perfPanel, ...
    'Text','TRANSMISSION INFORMATION', ...
    'Position',[20 345 290 25], ...
    'FontSize',12, ...
    'FontWeight','bold', ...
    'FontColor',DEEP);

perfText = uitextarea(perfPanel, ...
    'Position',[20 40 300 285], ...
    'Editable','off', ...
    'FontSize',12, ...
    'FontColor',TEXT, ...
    'BackgroundColor',BG);

perfText.Value = { ...
    'Message             --'; ...
    ''; ...
    'Characters          --'; ...
    'Total Bits          --'; ...
    'Bit Errors          --'; ...
    'BER                 --'; ...
    ''; ...
    'Modulation          OOK'; ...
    'Data Rate           10 kbps'; ...
    'SNR                 5 dB'; ...
    'Distance            2 m'; ...
    ''; ...
    'Transmission        READY'};

%% ================================================================
% CHANNEL ANALYSIS TAB
% ================================================================

uilabel(channelTab, ...
    'Text','CHANNEL ANALYSIS', ...
    'Position',[25 585 400 30], ...
    'FontSize',18, ...
    'FontWeight','bold', ...
    'FontColor',DEEP);

uilabel(channelTab, ...
    'Text','Optical channel behaviour with transmission distance', ...
    'Position',[25 558 650 22], ...
    'FontSize',12, ...
    'FontColor',TEXT_LIGHT);

powerCard = uipanel(channelTab, ...
    'Position',[25 315 575 225], ...
    'BackgroundColor',CARD, ...
    'BorderType','none');

uilabel(powerCard, ...
    'Text','RECEIVED OPTICAL POWER', ...
    'Position',[18 195 350 24], ...
    'FontSize',13, ...
    'FontWeight','bold', ...
    'FontColor',DEEP);

axPower = uiaxes(powerCard, ...
    'Position',[15 15 545 170], ...
    'BackgroundColor',BG);

title(axPower,'Received Optical Power vs Distance');
xlabel(axPower,'Distance (m)');
ylabel(axPower,'Received Optical Power (W)');
grid(axPower,'on');

gainCard = uipanel(channelTab, ...
    'Position',[615 315 575 225], ...
    'BackgroundColor',CARD, ...
    'BorderType','none');

uilabel(gainCard, ...
    'Text','OPTICAL CHANNEL GAIN', ...
    'Position',[18 195 350 24], ...
    'FontSize',13, ...
    'FontWeight','bold', ...
    'FontColor',DEEP);

axGain = uiaxes(gainCard, ...
    'Position',[15 15 545 170], ...
    'BackgroundColor',BG);

title(axGain,'LiFi Optical Channel Gain vs Distance');
xlabel(axGain,'Distance (m)');
ylabel(axGain,'Optical Channel Gain');
grid(axGain,'on');

channelPanel = uipanel(channelTab, ...
    'Position',[25 50 1165 245], ...
    'BackgroundColor',CARD_DARK, ...
    'BorderType','none');

uilabel(channelPanel, ...
    'Text','OPTICAL CHANNEL PARAMETERS', ...
    'Position',[20 210 350 25], ...
    'FontSize',13, ...
    'FontWeight','bold', ...
    'FontColor',DEEP);

channelText = uitextarea(channelPanel, ...
    'Position',[20 25 1125 170], ...
    'Editable','off', ...
    'FontSize',12, ...
    'FontColor',TEXT, ...
    'BackgroundColor',BG);

channelText.Value = { ...
    'Transmission Medium    Visible Light'; ...
    'Modulation             OOK (On-Off Keying)'; ...
    'Transmitter            LED'; ...
    'Receiver               Photodiode'; ...
    'Distance Range         0.5 m - 5 m'; ...
    'Message Distance       2 m'; ...
    'SNR                    5 dB'; ...
    'Channel Model          Distance-dependent attenuation + AWGN'};

%% ================================================================
% TRANSMISSION TAB
% ================================================================

uilabel(transmissionTab, ...
    'Text','TRANSMISSION PROCESS', ...
    'Position',[25 585 400 30], ...
    'FontSize',18, ...
    'FontWeight','bold', ...
    'FontColor',DEEP);

uilabel(transmissionTab, ...
    'Text','Live conversion: Text -> ASCII -> Binary -> OOK -> Optical Channel -> Photodiode -> Binary -> ASCII -> Text', ...
    'Position',[25 558 1120 22], ...
    'FontSize',12, ...
    'FontColor',TEXT_LIGHT);

conversionPanel = uipanel(transmissionTab, ...
    'Position',[25 55 760 485], ...
    'BackgroundColor',CARD, ...
    'BorderType','none');

uilabel(conversionPanel, ...
    'Text','CHARACTER CONVERSION', ...
    'Position',[20 445 300 25], ...
    'FontSize',13, ...
    'FontWeight','bold', ...
    'FontColor',DEEP);

conversionTable = uitable(conversionPanel, ...
    'Position',[20 205 720 225], ...
    'ColumnName',{'No.','Character','ASCII','8-bit Binary','TX OOK'}, ...
    'ColumnEditable',[false false false false false], ...
    'FontSize',11);

uilabel(conversionPanel, ...
    'Text','TRANSMISSION FLOW', ...
    'Position',[20 170 300 25], ...
    'FontSize',13, ...
    'FontWeight','bold', ...
    'FontColor',DEEP);

transmissionFlow = uitextarea(conversionPanel, ...
    'Position',[20 20 720 145], ...
    'Editable','off', ...
    'FontSize',12, ...
    'FontColor',TEXT, ...
    'BackgroundColor',BG);

transmissionFlow.Value = { ...
    'Waiting for a message...'; ...
    ''; ...
    'Press SEND VIA LiFi to see every conversion step.'};

livePanel = uipanel(transmissionTab, ...
    'Position',[810 55 370 485], ...
    'BackgroundColor',CARD_DARK, ...
    'BorderType','none');

uilabel(livePanel, ...
    'Text','LIVE TRANSMISSION', ...
    'Position',[20 445 300 25], ...
    'FontSize',13, ...
    'FontWeight','bold', ...
    'FontColor',DEEP);

transmissionStage = uilabel(livePanel, ...
    'Text','READY', ...
    'Position',[20 405 330 32], ...
    'FontSize',18, ...
    'FontWeight','bold', ...
    'FontColor',SUCCESS);

transmissionProgress = uilabel(livePanel, ...
    'Text','No transmission yet', ...
    'Position',[20 370 330 25], ...
    'FontSize',11, ...
    'FontColor',TEXT_LIGHT);

uilabel(livePanel, ...
    'Text','ASCII CONVERSION', ...
    'Position',[20 350 200 20], ...
    'FontSize',10, ...
    'FontWeight','bold', ...
    'FontColor',DEEP);

asciiLive = uitextarea(livePanel, ...
    'Position',[20 195 330 150], ...
    'Editable','off', ...
    'FontSize',11, ...
    'FontColor',TEXT, ...
    'BackgroundColor',BG);

uilabel(livePanel, ...
    'Text','TX BINARY STREAM', ...
    'Position',[20 180 200 20], ...
    'FontSize',10, ...
    'FontWeight','bold', ...
    'FontColor',DEEP);

bitStreamLive = uitextarea(livePanel, ...
    'Position',[20 35 330 140], ...
    'Editable','off', ...
    'FontSize',11, ...
    'FontColor',TEXT, ...
    'BackgroundColor',BG);

asciiLive.Value = {'ASCII conversion will appear here.'};

bitStreamLive.Value = {'TX bit stream will appear here.'};

%% ================================================================
% INITIAL GRAPHS
% ================================================================

updateGraphs("LiFi");

%% ================================================================
% STARTUP INFORMATION
% ================================================================

fprintf('\n===============================================================\n');
fprintf('              LiFi CHAT APPLICATION STARTED\n');
fprintf('===============================================================\n');
fprintf('Modulation : OOK (On-Off Keying)\n');
fprintf('Data Rate  : %s\n',DataRateText);
fprintf('SNR        : %.1f dB\n',SNR_dB);
fprintf('Distance   : %.1f m\n',ChannelDistance);
fprintf('===============================================================\n\n');

%% ================================================================
% SEND MESSAGE
% ================================================================

    function sendMessage(~,~)

        msg = strtrim(string(messageBox.Value));

        if strlength(msg) == 0

            statusMetric.Text = 'ENTER A MESSAGE';
            statusMetric.FontColor = ERROR;

            return;

        end

        if any(double(char(msg)) > 127)

            statusMetric.Text = 'ASCII TEXT ONLY';
            statusMetric.FontColor = ERROR;

            return;

        end

        if isvalid(emptyText)
            delete(emptyText);
        end

        %% ========================================================
        % TEXT -> ASCII -> BINARY
        % ========================================================

        asciiData = uint8(char(msg));

        bitMatrix = dec2bin(asciiData,8).' - '0';

        txBits = reshape(bitMatrix,1,[]);

        txBitsGlobal = txBits;

        transmissionStage.Text = ...
            '1. TEXT -> ASCII -> BINARY';

        transmissionStage.FontColor = LAVENDER;

        transmissionProgress.Text = ...
            sprintf('Encoding %d character(s)',strlength(msg));

        %% CHARACTER TABLE

        asciiRows = cell(length(asciiData),5);

        for ii = 1:length(asciiData)

            ch = char(asciiData(ii));

            binaryValue = dec2bin(asciiData(ii),8);

            asciiRows{ii,1} = ii;
            asciiRows{ii,2} = ch;
            asciiRows{ii,3} = double(asciiData(ii));
            asciiRows{ii,4} = binaryValue;

            ookText = binaryValue;

            ookText = strrep(ookText,'1','ON ');
            ookText = strrep(ookText,'0','OFF ');

            asciiRows{ii,5} = ookText;

        end

        conversionTable.Data = asciiRows;

        %% ASCII LIVE

        asciiLive.Value = { ...
            ['Original Text : ' char(msg)]; ...
            ''; ...
            'CHARACTER -> ASCII -> 8-BIT BINARY'; ...
            ''; ...
            sprintf('Characters : %d',length(asciiData)); ...
            ''; ...
            'Conversion:'};

        for ii = 1:length(asciiData)

            currentChar = char(asciiData(ii));
            currentASCII = double(asciiData(ii));
            currentBinary = dec2bin(asciiData(ii),8);

            asciiLive.Value{end+1} = sprintf( ...
                '%s -> %d -> %s', ...
                currentChar, ...
                currentASCII, ...
                currentBinary);

        end

        %% BIT STREAM

        bitStreamLive.Value = { ...
            'TX BINARY STREAM'; ...
            ''; ...
            num2str(txBits); ...
            ''; ...
            'OOK RULE:'; ...
            '1 = LED ON'; ...
            '0 = LED OFF'};

        drawnow;

        %% ========================================================
        % TRANSMISSION STATE
        % ========================================================

        statusHeader.Text = 'Transmitting...';
        statusHeader.FontColor = LED_RED;
        statusDot.FontColor = LED_RED;

        txStatus.Text = '● TRANSMITTING';
        txStatus.FontColor = LED_RED;

        rxStatus.Text = '● WAITING';
        rxStatus.FontColor = WARNING;

        statusMetric.Text = sprintf( ...
            'TRANSMITTING  •  %s  •  %.1f dB SNR', ...
            DataRateText,SNR_dB);

        statusMetric.FontColor = LED_RED;

        linkLabel.Text = 'TRANSMITTING...';
        linkLabel.FontColor = LED_RED;

        %% LED BLINK

        for blink = 1:6

            blinkState = ~blinkState;

            if blinkState

                ledIndicator.FontColor = LED_RED;
                photodiodeIndicator.FontColor = LED_IDLE;

            else

                ledIndicator.FontColor = LED_IDLE;
                photodiodeIndicator.FontColor = LED_RED;

            end

            drawnow;
            pause(0.12);

        end

        %% ========================================================
        % OOK MODULATION
        % ========================================================

        txSignal = repelem( ...
            double(txBits), ...
            SamplesPerBit);

        transmissionStage.Text = ...
            '2. BINARY -> OOK MODULATION';

        transmissionStage.FontColor = LAVENDER;

        transmissionProgress.Text = sprintf( ...
            'Sending %d optical samples at %s', ...
            length(txSignal),DataRateText);

        transmissionFlow.Value = { ...
            ['TEXT : ' char(msg)]; ...
            ''; ...
            'STEP 1 -> ASCII values'; ...
            'STEP 2 -> 8-bit binary'; ...
            'STEP 3 -> OOK modulation'; ...
            '          1 = LED ON'; ...
            '          0 = LED OFF'; ...
            sprintf('STEP 4 -> Optical channel at %.1f m',ChannelDistance); ...
            sprintf('          SNR = %.1f dB',SNR_dB); ...
            'STEP 5 -> Photodiode detection'; ...
            'STEP 6 -> Binary -> ASCII -> Text'; ...
            ''; ...
            'Transmission is in progress...'};

        drawnow;

        %% ========================================================
        % OPTICAL CHANNEL
        % ========================================================

        rng('shuffle');

        channelGain = ...
            (0.5/ChannelDistance)^2;

        attenuatedSignal = ...
            txSignal * channelGain;

        signalPower = ...
            max(mean(attenuatedSignal.^2),1e-6);

        noisePower = ...
            signalPower/(10^(SNR_dB/10));

        noise = ...
            sqrt(noisePower) * randn(size(attenuatedSignal));

        rxSignal = ...
            attenuatedSignal + noise;

        transmissionStage.Text = ...
            '3. OOK -> OPTICAL CHANNEL';

        transmissionStage.FontColor = LED_RED;

        transmissionProgress.Text = sprintf( ...
            'LED -> Channel -> Photodiode | Gain %.6f | SNR %.1f dB', ...
            channelGain,SNR_dB);

        drawnow;

        %% ========================================================
        % PHOTODIODE / DEMODULATION
        % ========================================================

        sampleIndex = ...
            round(SamplesPerBit/2): ...
            SamplesPerBit:length(rxSignal);

        rxSamples = ...
            rxSignal(sampleIndex);

        threshold = ...
            channelGain/2;

        rxBits = ...
            double(rxSamples >= threshold);

        %% OPTIONAL FORCED ERROR

        if FORCE_ERROR_DEMO

            errorMask = ...
                rand(size(rxBits)) < ...
                ForcedBitErrorProbability;

            rxBits(errorMask) = ...
                1 - rxBits(errorMask);

        end

        rxBitsGlobal = rxBits;

        transmissionStage.Text = ...
            '4. PHOTODIODE -> BINARY';

        transmissionStage.FontColor = LAVENDER;

        transmissionProgress.Text = sprintf( ...
            'Threshold = %.6f | Received %d bits', ...
            threshold,length(rxBits));

        drawnow;

        %% ========================================================
        % BER
        % ========================================================

        bitErrorsGlobal = ...
            sum(txBits ~= rxBits);

        berGlobal = ...
            bitErrorsGlobal / max(length(txBits),1);

        %% ========================================================
        % BINARY -> ASCII -> TEXT
        % ========================================================

        rxMatrix = ...
            reshape(rxBits,8,[]).';

        rxASCII = ...
            uint8(bin2dec(char(rxMatrix + '0')));

        receivedMessage = ...
            string(char(rxASCII.'));

        %% RX TABLE

        rxRows = cell(length(rxASCII),5);

        for ii = 1:length(rxASCII)

            currentChar = char(rxASCII(ii));
            currentASCII = double(rxASCII(ii));
            currentBinary = dec2bin(rxASCII(ii),8);

            startBit = (ii-1)*8 + 1;
            endBit = ii*8;

            txCharBits = txBits(startBit:endBit);
            rxCharBits = rxBits(startBit:endBit);

            charErrors = ...
                sum(txCharBits ~= rxCharBits);

            rxRows{ii,1} = ii;
            rxRows{ii,2} = currentChar;
            rxRows{ii,3} = currentASCII;
            rxRows{ii,4} = currentBinary;

            rxRows{ii,5} = ...
                sprintf('%d error(s)',charErrors);

        end

        conversionTable.ColumnName = ...
            {'No.','RX Character','RX ASCII','RX Binary','Result'};

        conversionTable.Data = rxRows;

        %% ========================================================
        % FINAL TRANSMISSION FLOW
        % ========================================================

        if bitErrorsGlobal == 0

            transmissionStage.Text = ...
                'TRANSMISSION SUCCESSFUL';

            transmissionStage.FontColor = SUCCESS;

        else

            transmissionStage.Text = ...
                'TRANSMISSION WITH ERRORS';

            transmissionStage.FontColor = ERROR;

        end

        transmissionProgress.Text = sprintf( ...
            'TX -> RX complete | %d errors | BER %.6f', ...
            bitErrorsGlobal,berGlobal);

        transmissionFlow.Value = { ...
            ['TEXT : ' char(msg)]; ...
            ''; ...
            'TRANSMITTER'; ...
            'Text -> ASCII -> Binary -> OOK'; ...
            ''; ...
            sprintf('Channel Distance : %.1f m',ChannelDistance); ...
            sprintf('SNR              : %.1f dB',SNR_dB); ...
            sprintf('Data Rate         : %s',DataRateText); ...
            ''; ...
            'RECEIVER'; ...
            'Photodiode -> Threshold -> Binary'; ...
            'Binary -> ASCII -> Text'; ...
            ''; ...
            ['Received Text : ' char(receivedMessage)]; ...
            sprintf('Bit Errors    : %d',bitErrorsGlobal); ...
            sprintf('BER           : %.6f',berGlobal)};

        asciiLive.Value{end+1} = '';
        asciiLive.Value{end+1} = ...
            ['RECEIVED TEXT : ' char(receivedMessage)];

        bitStreamLive.Value{end+1} = '';
        bitStreamLive.Value{end+1} = 'RX BINARY STREAM';
        bitStreamLive.Value{end+1} = num2str(rxBits);

        drawnow;

        %% ========================================================
        % CHAT HISTORY
        % ========================================================

        tnow = datestr(now,'HH:MM');

        messageHistory{end+1} = char(msg);
        timeHistory{end+1} = tnow;

        transmittedHistory{end+1} = char(msg);
        receivedHistory{end+1} = char(receivedMessage);

        renderChatHistory();

        %% ========================================================
        % RECEIVER STATE
        % ========================================================

        statusHeader.Text = 'Receiving...';
        statusHeader.FontColor = DEEP;

        txStatus.Text = '● SENT';
        txStatus.FontColor = SUCCESS;

        rxStatus.Text = '● RECEIVING';
        rxStatus.FontColor = LAVENDER;

        statusMetric.Text = ...
            'RECEIVING  •  PHOTODIODE';

        statusMetric.FontColor = LAVENDER;

        linkLabel.Text = ...
            'OPTICAL SIGNAL DETECTED';

        linkLabel.FontColor = LAVENDER;

        %% PHOTODIODE ACTIVITY

        for k = 1:4

            photodiodeIndicator.FontColor = LED_RED;

            drawnow;
            pause(0.10);

            photodiodeIndicator.FontColor = LED_IDLE;

            drawnow;
            pause(0.08);

        end

        %% ========================================================
        % FINAL STATUS
        % ========================================================

        statusHeader.Text = ...
            'LiFi Connected';

        statusHeader.FontColor = SUCCESS;
        statusDot.FontColor = SUCCESS;

        ledIndicator.FontColor = LED_GREEN;
        photodiodeIndicator.FontColor = LED_GREEN;

        txStatus.Text = '● READY';
        txStatus.FontColor = SUCCESS;

        if bitErrorsGlobal == 0

            rxStatus.Text = '● MESSAGE RECEIVED';
            rxStatus.FontColor = SUCCESS;

            statusMetric.Text = ...
                'SUCCESS  |  MESSAGE RECEIVED';

            statusMetric.FontColor = SUCCESS;

            linkLabel.Text = ...
                'LINK ACTIVE  •  DATA RECEIVED';

            linkLabel.FontColor = SUCCESS;

        else

            rxStatus.Text = '● ERRORS DETECTED';
            rxStatus.FontColor = ERROR;

            statusMetric.Text = sprintf( ...
                'RECEIVED WITH %d BIT ERROR(S)', ...
                bitErrorsGlobal);

            statusMetric.FontColor = ERROR;

            linkLabel.Text = ...
                'LINK ACTIVE  •  BIT ERRORS PRESENT';

            linkLabel.FontColor = ERROR;

        end

        %% ========================================================
        % UPDATE METRICS
        % ========================================================

        messageMetric.Text = char(msg);

        bitsMetric.Text = ...
            sprintf('%d',length(txBits));

        berMetric.Text = ...
            sprintf('%.4f',berGlobal);

        berCard.UserData.Text = ...
            sprintf('%.4f',berGlobal);

        errorCard.UserData.Text = ...
            sprintf('%d',bitErrorsGlobal);

        snrCard.UserData.Text = ...
            sprintf('%.1f dB',SNR_dB);

        throughputCard.UserData.Text = ...
            DataRateText;

        %% PERFORMANCE

        perfText.Value = { ...
            ['Message             ' char(msg)]; ...
            ''; ...
            sprintf('Characters          %d',strlength(msg)); ...
            sprintf('Total Bits          %d',length(txBits)); ...
            sprintf('Bit Errors          %d',bitErrorsGlobal); ...
            sprintf('BER                 %.4f',berGlobal); ...
            ''; ...
            'Modulation          OOK'; ...
            ['Data Rate           ' DataRateText]; ...
            sprintf('SNR                 %.1f dB',SNR_dB); ...
            sprintf('Distance            %.1f m',ChannelDistance); ...
            ''; ...
            'Transmission        COMPLETED'};

        %% ACTUAL GRAPHS

        updateGraphs( ...
            msg, ...
            txSignal, ...
            rxSignal, ...
            txBits, ...
            rxBits);

        messageBox.Value = '';

    end

%% ================================================================
% DATA RATE CONTROL
% ================================================================

    function dataRateChanged(src,~)

        DataRateText = char(src.Value);

        DataRate = sscanf(DataRateText,'%f');

        dataRateDetail.Text = DataRateText;

        throughputCard.UserData.Text = DataRateText;

        perfText.Value = { ...
            'Message             --'; ...
            ''; ...
            'Characters          --'; ...
            'Total Bits          --'; ...
            'Bit Errors          --'; ...
            'BER                 --'; ...
            ''; ...
            'Modulation          OOK'; ...
            ['Data Rate           ' DataRateText]; ...
            sprintf('SNR                 %.1f dB',SNR_dB); ...
            sprintf('Distance            %.1f m',ChannelDistance); ...
            ''; ...
            'Transmission        READY'};

        statusMetric.Text = ...
            ['READY  •  ' DataRateText];

        statusMetric.FontColor = SUCCESS;

        drawnow;

    end

%% ================================================================
% SNR CONTROL
% ================================================================

    function snrChanged(src,~)

        SNRText = char(src.Value);

        SNR_dB = sscanf(SNRText,'%f');

        snrDetail.Text = ...
            sprintf('%.1f dB',SNR_dB);

        snrCard.UserData.Text = ...
            sprintf('%.1f dB',SNR_dB);

        channelText.Value = { ...
            'Transmission Medium    Visible Light'; ...
            'Modulation             OOK (On-Off Keying)'; ...
            'Transmitter            LED'; ...
            'Receiver               Photodiode'; ...
            'Distance Range         0.5 m - 5 m'; ...
            sprintf('Message Distance       %.1f m',ChannelDistance); ...
            sprintf('SNR                    %.1f dB',SNR_dB); ...
            'Channel Model          Distance-dependent attenuation + AWGN'};

        perfText.Value = { ...
            'Message             --'; ...
            ''; ...
            'Characters          --'; ...
            'Total Bits          --'; ...
            'Bit Errors          --'; ...
            'BER                 --'; ...
            ''; ...
            'Modulation          OOK'; ...
            ['Data Rate           ' DataRateText]; ...
            sprintf('SNR                 %.1f dB',SNR_dB); ...
            sprintf('Distance            %.1f m',ChannelDistance); ...
            ''; ...
            'Transmission        READY'};

        statusMetric.Text = ...
            sprintf('READY  •  SNR %.1f dB',SNR_dB);

        statusMetric.FontColor = SUCCESS;

        %% Refresh graphs immediately

        updateGraphs("LiFi");

        drawnow;

    end

%% ================================================================
% CHAT BUBBLE
% ================================================================

    function addChatBubble(messageText,type,msgTime)

        if strcmp(type,'TX')

            if isempty(transmittedHistory) || ...
                    ~strcmp(transmittedHistory{end},messageText)

                transmittedHistory{end+1} = messageText;
                receivedHistory{end+1} = '';
                messageHistory{end+1} = messageText;
                timeHistory{end+1} = msgTime;

            end

        end

        renderChatHistory();

    end

%% ================================================================
% RENDER CHAT
% ================================================================

    function renderChatHistory()

        oldChildren = chatDisplay.Children;

        for i = 1:length(oldChildren)

            obj = oldChildren(i);

            if isvalid(obj) && ...
                    isprop(obj,'Tag') && ...
                    strcmp(obj.Tag,'chatbubble')

                delete(obj);

            end

        end

        count = numel(transmittedHistory);

        if count == 0
            return;
        end

        startIndex = max(1,count-3);

        yRight = 285;
        yLeft = 285;

        for k = startIndex:count

            txText = transmittedHistory{k};

            rxText = '';

            if k <= numel(receivedHistory)
                rxText = receivedHistory{k};
            end

            msgTime = timeHistory{k};

            %% TX BUBBLE

            bubbleWidth = ...
                min(430,max(240,100 + 7*length(txText)));

            bubble = uipanel(chatDisplay, ...
                'Position',[880-bubbleWidth-20 ...
                            yRight ...
                            bubbleWidth ...
                            65], ...
                'BackgroundColor',TX_BUBBLE, ...
                'BorderType','none', ...
                'Tag','chatbubble');

            uilabel(bubble, ...
                'Text','YOU  •  TRANSMITTER', ...
                'Position',[12 40 bubbleWidth-24 18], ...
                'FontSize',10, ...
                'FontWeight','bold', ...
                'FontColor',DEEP);

            uilabel(bubble, ...
                'Text',txText, ...
                'Position',[12 18 bubbleWidth-24 23], ...
                'FontSize',13, ...
                'FontColor',TEXT);

            uilabel(bubble, ...
                'Text',[msgTime '   ✓✓'], ...
                'Position',[bubbleWidth-90 3 80 16], ...
                'HorizontalAlignment','right', ...
                'FontSize',9, ...
                'FontColor',TEXT_LIGHT);

            yRight = yRight - 78;

            %% RX BUBBLE

            if ~isempty(rxText)

                bubbleWidth = ...
                    min(430,max(240,110 + 7*length(rxText)));

                bubble = uipanel(chatDisplay, ...
                    'Position',[20 yLeft bubbleWidth 65], ...
                    'BackgroundColor',RX_BUBBLE, ...
                    'BorderType','none', ...
                    'Tag','chatbubble');

                uilabel(bubble, ...
                    'Text','LiFi RECEIVER', ...
                    'Position',[12 40 bubbleWidth-24 18], ...
                    'FontSize',10, ...
                    'FontWeight','bold', ...
                    'FontColor',DEEP);

                uilabel(bubble, ...
                    'Text',rxText, ...
                    'Position',[12 18 bubbleWidth-24 23], ...
                    'FontSize',13, ...
                    'FontColor',TEXT);

                uilabel(bubble, ...
                    'Text',[msgTime '   ✓'], ...
                    'Position',[bubbleWidth-80 3 70 16], ...
                    'HorizontalAlignment','right', ...
                    'FontSize',9, ...
                    'FontColor',TEXT_LIGHT);

                yLeft = yLeft - 78;

            end

        end

        drawnow;

    end

%% ================================================================
% UPDATE GRAPHS
% ================================================================

    function updateGraphs( ...
            msg, ...
            txSignalInput, ...
            rxSignalInput, ...
            txBitsInput, ...
            rxBitsInput)

        %% TEXT -> BITS

        asciiData = uint8(char(msg));

        bitMatrix = dec2bin(asciiData,8).' - '0';

        bits = reshape(bitMatrix,1,[]);

        %% CREATE SIGNAL IF NOT PROVIDED

        if nargin < 2 || isempty(txSignalInput)

            txSignal = ...
                repelem(double(bits),SamplesPerBit);

            rng(10);

            gainForGraph = ...
                (0.5/ChannelDistance)^2;

            attenuated = ...
                txSignal * gainForGraph;

            signalPower = ...
                max(mean(attenuated.^2),1e-6);

            noisePower = ...
                signalPower/(10^(SNR_dB/10));

            noise = ...
                sqrt(noisePower)*randn(size(attenuated));

            rxSignal = ...
                attenuated + noise;

            sampleIndex = ...
                round(SamplesPerBit/2): ...
                SamplesPerBit:length(rxSignal);

            rxSamples = ...
                rxSignal(sampleIndex);

            threshold = gainForGraph/2;

            rxBits = ...
                double(rxSamples >= threshold);

        else

            txSignal = txSignalInput;
            rxSignal = rxSignalInput;
            rxBits = rxBitsInput;

        end

        sample = 1:length(txSignal);

        %% TX GRAPH

        cla(axTX);

        plot(axTX, ...
            sample, ...
            txSignal, ...
            'LineWidth',1.7, ...
            'Color',LAVENDER);

        ylim(axTX,[-0.2 1.2]);

        title(axTX, ...
            'Transmitted OOK Signal', ...
            'FontSize',13);

        xlabel(axTX,'Sample');
        ylabel(axTX,'LED Intensity');

        grid(axTX,'on');

        %% RX GRAPH

        cla(axRX);

        plot(axRX, ...
            sample, ...
            rxSignal, ...
            'LineWidth',0.9, ...
            'Color',DEEP);

        hold(axRX,'on');

        gainForGraph = ...
            (0.5/ChannelDistance)^2;

        threshold = ...
            gainForGraph/2;

        yline(axRX, ...
            threshold, ...
            '--', ...
            'Threshold', ...
            'LineWidth',1.1, ...
            'Color',LAVENDER);

        hold(axRX,'off');

        title(axRX, ...
            sprintf('Received Signal - SNR = %.1f dB',SNR_dB), ...
            'FontSize',13);

        xlabel(axRX,'Sample');
        ylabel(axRX,'Photodiode Output');

        grid(axRX,'on');

        %% TX VS RX

        cla(axBits);

        bitNumber = 1:length(bits);

        plot(axBits, ...
            bitNumber, ...
            bits, ...
            'o-', ...
            'LineWidth',1.3, ...
            'MarkerSize',5, ...
            'Color',LAVENDER);

        hold(axBits,'on');

        plot(axBits, ...
            bitNumber, ...
            rxBits, ...
            'o--', ...
            'LineWidth',1.3, ...
            'MarkerSize',4, ...
            'Color',DEEP);

        errorPositions = find(bits ~= rxBits);

        if ~isempty(errorPositions)

            plot(axBits, ...
                errorPositions, ...
                rxBits(errorPositions), ...
                'x', ...
                'MarkerSize',10, ...
                'LineWidth',2, ...
                'Color',ERROR);

        end

        hold(axBits,'off');

        title(axBits, ...
            sprintf('Transmitted vs Received Bits - Errors = %d', ...
            sum(bits ~= rxBits)), ...
            'FontSize',13);

        xlabel(axBits,'Bit Number');
        ylabel(axBits,'Bit Value');

        ylim(axBits,[-0.2 1.2]);

        legend(axBits, ...
            {'Transmitted Bits','Received Bits','Bit Errors'}, ...
            'Location','best');

        grid(axBits,'on');

        %% ========================================================
        % BER VS DISTANCE
        % ========================================================

        berDistance = zeros(size(Distance));

        rng(25);

        testBits = randi([0 1],5000,1);

        for k = 1:length(Distance)

            d = Distance(k);

            gain = (0.5/d)^2;

            received = double(testBits)*gain;

            signalPowerD = ...
                max(mean(received.^2),1e-9);

            noisePowerD = ...
                signalPowerD/(10^(SNR_dB/10));

            noiseD = ...
                sqrt(noisePowerD)*randn(size(received));

            received = ...
                received + noiseD;

            thresholdD = gain/2;

            recovered = ...
                received >= thresholdD;

            berDistance(k) = ...
                mean(recovered ~= testBits);

        end

        berDistance = ...
            max(berDistance,1e-5);

        cla(axBER);

        semilogy(axBER, ...
            Distance, ...
            berDistance, ...
            'o-', ...
            'LineWidth',1.7, ...
            'MarkerSize',6, ...
            'Color',LAVENDER);

        title(axBER, ...
            sprintf('BER vs Distance - SNR = %.1f dB',SNR_dB), ...
            'FontSize',14);

        xlabel(axBER,'Distance (m)');
        ylabel(axBER,'Bit Error Rate (BER)');

        ylim(axBER,[1e-5 1]);

        grid(axBER,'on');

        %% ========================================================
        % CHANNEL GAIN
        % ========================================================

        channelGain = ...
            (0.5./Distance).^2;

        %% RECEIVED POWER
        % ========================================================

        P_LED = 1;

        receivedPower = ...
            P_LED * channelGain * 1e-4;

        cla(axPower);

        plot(axPower, ...
            Distance, ...
            receivedPower, ...
            'o-', ...
            'LineWidth',1.7, ...
            'MarkerSize',6, ...
            'Color',LAVENDER);

        title(axPower, ...
            'Received Optical Power vs Distance', ...
            'FontSize',13);

        xlabel(axPower,'Distance (m)');
        ylabel(axPower,'Received Optical Power (W)');

        grid(axPower,'on');

        %% ========================================================
        % CHANNEL GAIN GRAPH
        % ========================================================

        cla(axGain);

        plot(axGain, ...
            Distance, ...
            channelGain, ...
            'o-', ...
            'LineWidth',1.7, ...
            'MarkerSize',6, ...
            'Color',DEEP);

        title(axGain, ...
            'LiFi Optical Channel Gain vs Distance', ...
            'FontSize',13);

        xlabel(axGain,'Distance (m)');
        ylabel(axGain,'Optical Channel Gain');

        grid(axGain,'on');

    end

%% ================================================================
% METRIC CARD
% ================================================================

    function panel = createMetricCard( ...
            parent, ...
            pos, ...
            titleText, ...
            valueText)

        panel = uipanel(parent, ...
            'Position',pos, ...
            'BackgroundColor',CARD, ...
            'BorderType','none');

        uilabel(panel, ...
            'Text',titleText, ...
            'Position',[15 38 230 18], ...
            'FontSize',9, ...
            'FontWeight','bold', ...
            'FontColor',TEXT_LIGHT);

        valueLabel = uilabel(panel, ...
            'Text',valueText, ...
            'Position',[15 8 230 28], ...
            'FontSize',17, ...
            'FontWeight','bold', ...
            'FontColor',DEEP);

        panel.UserData = valueLabel;

    end

end